export const de = {
  languageName: "Deutsch (Schweiz)",
  system: {
    ready: "Alles klar, los geht’s.",
    saved: "Speichern abgeschlossen.",
    error: "Ups… da ging was schief.",
    loading: "Lade Daten…",
    noData: "Keine Daten gefunden."
  },
  auth: {
    login: "Einloggen",
    email: "E‑Mail",
    password: "Passwort eingeben",
    in: "Du bist jetzt drin.",
    out: "Du bist jetzt draussen.",
    disabled: "Dein Konto ist deaktiviert.",
    skip: "Intro überspringen"
  },
  nav: {
    dashboard: "Dashboard",
    analysis: "Übersicht & Dashboard",
    employees: "Mitarbeiter",
    products: "Produkte",
    tasks: "Aufgaben",
    time: "Zeiterfassung",
    support: "Support",
    admin: "Admin Panel",
    logout: "Logout"
  },
  roles: {
    admin: "Administrator",
    manager: "Manager",
    support: "Support",
    employee: "Mitarbeiter",
    guest: "Gast"
  },
  admin: {
    createUser: "Neuen Benutzer erstellen",
    deleteUser: "Benutzer löschen",
    changeRole: "Rolle ändern",
    saved: "Alles gespeichert.",
    confirm: "Bist du sicher?",
    emailInUse: "Diese E‑Mail wird bereits verwendet.",
    invalidEmail: "Ungültige E‑Mail-Adresse.",
    weakPassword: "Passwort ist zu schwach.",
    auditLog: "Audit Log",
    refresh: "Aktualisieren",
    searchAudit: "Suche im Audit Log…"
  },
  dashboard: {
    overview: "Übersicht",
    analysis: "Übersicht & Dashboard",
    totalProducts: "Total Produkte",
    totalEmployees: "Total Mitarbeiter",
    totalTasks: "Total Aufgaben",
    totalHours: "Total Stunden",
    totalTickets: "Total Tickets",
    quickLinks: "Direktzugriff",
    quickProducts: "Verwalte deine Artikel und Bestände.",
    quickTasks: "Organisiere deine To‑Dos und Teamaufgaben.",
    quickTime: "Behalte deine Arbeitszeit im Blick.",
    quickEmployees: "Pflege und verwalte deine Teamdaten.",
    quickSupport: "Bearbeite Supportfälle und Tickets.",
    quickAdmin: "Verwalte Benutzer und Rollen.",
    openProducts: "Produktverwaltung öffnen",
    openTasks: "Aufgabenmanagement öffnen",
    openTime: "Zeiterfassung öffnen",
    openEmployees: "Mitarbeiterverwaltung öffnen",
    openSupport: "Support öffnen",
    openAdmin: "Admin Panel öffnen"
  },
  employees: {
    title: "Mitarbeiterverwaltung",
    new: "Neuen Mitarbeiter hinzufügen",
    overview: "Mitarbeiterübersicht",
    number: "Nummer",
    name: "Name",
    email: "E‑Mail",
    phone: "Telefon",
    address: "Adresse",
    birthday: "Geburtstag",
    id: "Mitarbeiter‑Nr.",
    role: "Rolle",
    status: "Status",
    save: "Mitarbeiter speichern",
    actions: "Aktionen",
    delete: "Löschen",
    edit: "Bearbeiten",
    disable: "Deaktivieren",
    enable: "Aktivieren",
    disabled: "Deaktiviert",
    enabled: "Aktiv",
    active: "Aktiv"
  },
  products: {
    title: "Produktverwaltung",
    add: "Neues Produkt hinzufügen",
    overview: "Produktübersicht",
    name: "Produktname",
    description: "Beschreibung",
    type: "Typ",
    vendor: "Anbieter",
    collections: "Kollektionen",
    sku: "SKU",
    ean: "EAN",
    stock: "Bestand",
    price: "Preis (CHF)",
    category: "Kategorie",
    updateStock: "Bestand aktualisieren",
    save: "Speichern",
    export: "Exportieren für Shopify",
    delete: "Löschen",
    actions: "Aktionen",
    deleteAll: "Alles löschen",
    confirmDelete: "Möchtest du dieses Produkt wirklich löschen?",
    confirmYes: "Ja, löschen",
    confirmNo: "Abbrechen",
    cancel: "Abbrechen",
    saved: "Produkt gespeichert.",
    edit: "Bearbeiten"
  },
  tasks: {
    title: "Aufgabenverwaltung",
    new: "Neue Aufgabe erstellen",
    overview: "Aufgabenübersicht",
    name: "Aufgabe",
    description: "Beschreibung",
    status: "Status",
    assignedTo: "Zugewiesen an",
    dueDate: "Fälligkeitsdatum",
    priority: "Priorität",
    save: "Aufgabe speichern",
    delete: "Löschen",
    edit: "Bearbeiten",
    actions: "Aktionen",
    completed: "Erledigt",
    open: "Offen"
  },
  time: {
    title: "Zeiterfassung",
    overview: "Zeiterfassungsübersicht",
    start: "Start",
    stop: "Stopp",
    duration: "Dauer",
    date: "Datum",
    project: "Projekt",
    note: "Notiz",
    save: "Zeit speichern",
    delete: "Löschen",
    edit: "Bearbeiten",
    actions: "Aktionen"
  },
  support: {
    title: "Support",
    new: "Neues Ticket erstellen",
    overview: "Supportübersicht",
    ticketId: "Ticket‑Nr.",
    subject: "Betreff",
    message: "Nachricht",
    status: "Status",
    assignedTo: "Bearbeiter",
    createdAt: "Erstellt am",
    save: "Ticket speichern",
    delete: "Löschen",
    edit: "Bearbeiten",
    actions: "Aktionen",
    open: "Offen",
    closed: "Geschlossen"
  }
};
