export const en = {
  languageName: "English",
  system: {
    ready: "Alright, let’s go.",
    saved: "Saved.",
    error: "Oops… something went wrong.",
    loading: "Loading…",
    noData: "No data found."
  },
  auth: {
    login: "Sign in",
    email: "Email",
    password: "Enter your password",
    in: "You’re in.",
    out: "You’re out.",
    disabled: "Your account is disabled.",
    skip: "Skip intro"
  },
  nav: {
    dashboard: "Dashboard",
    analysis: "Overview & dashboard",
    employees: "Employees",
    products: "Products",
    tasks: "Tasks",
    time: "Time tracking",
    support: "Support",
    admin: "Admin Panel",
    logout: "Logout"
  },
  roles: {
    admin: "Administrator",
    manager: "Manager",
    support: "Support",
    employee: "Employee",
    guest: "Guest"
  },
  admin: {
    createUser: "Create new user",
    deleteUser: "Delete user",
    changeRole: "Change role",
    saved: "All set.",
    confirm: "Are you sure?",
    emailInUse: "This email is already in use.",
    invalidEmail: "Invalid email address.",
    weakPassword: "Password is too weak.",
    auditLog: "Audit Log",
    refresh: "Refresh",
    searchAudit: "Search audit log…"
  },
  dashboard: {
    overview: "Overview",
    analysis: "Overview & dashboard",
    totalProducts: "Total products",
    totalEmployees: "Total employees",
    totalTasks: "Total tasks",
    totalHours: "Total hours",
    totalTickets: "Total tickets",
    quickLinks: "Quick access",
    quickProducts: "Manage your products and stock.",
    quickTasks: "Organize your tasks and team work.",
    quickTime: "Track your working hours.",
    quickEmployees: "Manage your team data.",
    quickSupport: "Handle support tickets.",
    quickAdmin: "Manage users and roles.",
    openProducts: "Open product management",
    openTasks: "Open task management",
    openTime: "Open time tracking",
    openEmployees: "Open employee management",
    openSupport: "Open support",
    openAdmin: "Open admin panel"
  },
  employees: {
    title: "Employee management",
    new: "Add new employee",
    overview: "Employee overview",
    number: "Number",
    name: "Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    birthday: "Birthday",
    id: "Employee ID",
    role: "Role",
    status: "Status",
    save: "Save employee",
    actions: "Actions",
    delete: "Delete",
    edit: "Edit",
    disable: "Disable",
    enable: "Enable",
    disabled: "Disabled",
    enabled: "Active",
    active: "Active"
  },
  products: {
    title: "Product management",
    add: "Add new product",
    overview: "Product overview",
    name: "Product name",
    description: "Description",
    type: "Type",
    vendor: "Vendor",
    collections: "Collections",
    sku: "SKU",
    ean: "EAN",
    stock: "Stock",
    price: "Price (CHF)",
    category: "Category",
    updateStock: "Update stock",
    save: "Save",
    export: "Export for Shopify",
    delete: "Delete",
    actions: "Actions",
    deleteAll: "Delete all",
    confirmDelete: "Do you really want to delete this product?",
    confirmYes: "Yes, delete",
    confirmNo: "Cancel",
    cancel: "Cancel",
    saved: "Product saved.",
    edit: "Edit"
  },
  tasks: {
    title: "Task management",
    new: "Create new task",
    overview: "Task overview",
    name: "Task",
    description: "Description",
    status: "Status",
    assignedTo: "Assigned to",
    dueDate: "Due date",
    priority: "Priority",
    save: "Save task",
    delete: "Delete",
    edit: "Edit",
    actions: "Actions",
    completed: "Completed",
    open: "Open"
  },
  time: {
    title: "Time tracking",
    overview: "Time overview",
    start: "Start",
    stop: "Stop",
    duration: "Duration",
    date: "Date",
    project: "Project",
    note: "Note",
    save: "Save time",
    delete: "Delete",
    edit: "Edit",
    actions: "Actions"
  },
  support: {
    title: "Support",
    new: "Create new ticket",
    overview: "Support overview",
    ticketId: "Ticket ID",
    subject: "Subject",
    message: "Message",
    status: "Status",
    assignedTo: "Assigned to",
    createdAt: "Created at",
    save: "Save ticket",
    delete: "Delete",
    edit: "Edit",
    actions: "Actions",
    open: "Open",
    closed: "Closed"
  }
};
